### ISSUE TITLE
Claimed features are impossible and / or illegal

### ISSUE THREAD

**Issue by CanadaHonk** [hxr404/Discord-Oxygen#19]
Hey there, many of the claimed features in README are impossible, or at least very misleading. Technically you can do some of these but it would only be client-side for the user or not properly. For example:
> Changeable discriminator

You can't actually change it without Nitro, best you could do is use a fake one for users of "Discord Oxygen". Etc for other such similar ones.

> Bypass MFA
> Discord Mobile QR Exploit
> Log into other people's accounts READ-ONLY... just by sending a link (by exploiting a flaw in Discord's authentication system)
> Fetch private information

You are making baseless claims of serious security vulnerabilities which don't exist. Plus, use of them would be illegal and immoral.

Also linking people to sponsor you for a project which doesn't exist, or if it does simply cannot do what is stated it can / does accomplish is at best just a scam. Please consider risks and / or consequences of stating things like such quoted in your README when it is misleading at best and just illegal + immoral sometimes. Thank you.

**Comment by yeehawbeef** [comment]
He's probably gonna close this without answering because he has no answer for this.

**Comment by Sxvxgee** [comment]
this repo is full of shit fr, if it was possible to do what he is claiming, people would've done it ages before him

**Comment by kekkodance** [comment]
you do not simply "find a exploit" to do all this stuff, some of the features you claim are "innovative" or "incredible" such as finding channel id's or bypassing NSFW locks are already done by other client mods, which your "client mod" isnt one.
i wouldnt be surprised if this was a rebranded version of BD with a logger hidden inside it.

**Comment by Sxvxgee** [comment]
On god. I mean with the attention this project has gotten, the chances of the actual product having a logger and/or a virus should be taken into consideration and not simply forgotten. Especially since the source code isn't going public.

**Comment by yeehawbeef** [comment]
Also, about him saying that he won't make it open source because of skids, he can literally just put his credits into the software, and skids don't know anything about actual programming so there will be no way for them to remove the credits. This is more proof that it's probably a token logger.

**Comment by Sxvxgee** [comment]
Exactly. Code can obfuscated and he won't have to worry about skids stealing his code and shit. Most a skid can do is find credits and change them to his own, but I doubt they would change anything about the whole client other than pre-set variables and data, or remove functions and ruin the whole program. This whole thing is a lie.

**Comment by hxr404** [comment]
@Anonymous941 
> one chance to prove yourself

I don't have to "prove" anything, I'm not forcing you or anyone to use this project or to donate. If you don't like this project stop thinking about it and just move on.


Also just because I can't reply to this thread within 4 days, it doesn't mean I'm ignoring it.


I'm only gonna reply to people with real feedback here, not to random accusations.


Something like

> this repo is full of shit fr, if it was possible to do what he is claiming, people would've done it ages before him
@Sxvxgee

doesn't contribute anything to this discussion and is at best off-topic, if not inappropriate, GitHub is a platform for Software Development, not for people getting mad about nothing.
That's why I'm not gonna reply to comments like these.

<hr>

So now I'm gonna reply to the only useful feedback in this issue:
First of all, thanks @CanadaHonk for your honest and neutral feedback, I appreciate that there are still people here who can say something without insults.


> best you could do is use a fake one for users of "Discord Oxygen".
And that's exactly the thing I'm doing here with this project. Most features that aren't possible "for real" are done client-side / changes only displays to other Discord Oxygen users.

other examples you mentioned are indeed possible,
for example the "Discord Mobile QR Exploit" is not only possible, but has been implemented by many other projects already. (Perhaps the lack of explanation what this exploit actually does could be misleading? I'm not really sure, because to me it seems self-explanatory)
This thing simply works by generating a QR Code which grants access to someone's account if scanned. It doesn't work remotely and isn't a zero-day it needs to be scanned by the "victim", so I don't really get why this couldn't be possible.
Things like "Fetch private information" also aren't really hard to do, I mean if you consider seeing the permissions of hidden channels private then literally anyone could do it. (I don't, but still)
One example of what that "exploit" does is monitoring the online / offline schedules of a specific user, and that's in my opinion really private information.

> Plus, use of them would be illegal and immoral.

That's why some of them are marked as private-only. And besides, how should some harmless client-modifications be illegal? I don't use any of Discord's assets or code, so there is no copyright infringement and even if some of the features were illegal (which I doubt they are, nobody is gonna get into jail for violating some Terms of Service), *I* am only publishing them, I'm not the one using them.
(Currently I'm not even publishing them, I only post *names* of features on a README, that isn't illegal and shouldn't be if freedom of speech exists.)

I really understand your concerns that some of the features may be immoral to use because discord is selling them and if people would get it for free it *could* harm discord's business.
But I carefully thought about this and I came to the conclusion, that this project won't harm Discord's revenue. I don't think people would stop buying Nitro just because some of it's features are made available by some random third-party. And, perhaps the most important reason, the target audience of this project are certainly not people who genuinely want to buy Nitro. Most people who see this repo come here, because they *don't* want to buy Nitro. So if they already made the decision that they don't want to buy it, this project doesn't change anything.
-> Therefore no loss for Discord but better user experience for some users. That's a win-win situation imho.
And if someone would lose their account due to the usage of this project, its a risk the user has to consider. I explicitly warn about that risk and everyone has to decide on their own.
Even though its not nice to loose an account, I don't think that's something immoral to support, especially not if the user makes an informed decision to take/not take that risk.

And to address your last argument that linking a sponsor button to this project might be "at best a scam" I have multiple answers.
1. "at best"? What could possibly be worse than a scam? I don't really understood what you wanted to say there, a clarification would be appreciated.
2. I have to disagree that this project couldn't accomplish what is stated on the readme. Even if things like changing a discriminator isn't possible globally, it *is* indeed possible to do that client-side and for other users of Discord Oxygen. So maybe the misunderstanding here is the definition of accomplishing things. I personally think, that if something works client-side and for other users of Discord Oxygen it is "accomplished". But yes, I have to agree with you that this maybe should be clarified a bit, as things looking obvious to me might not be obvious for many others, so thanks for pointing that out.
3. The sponsorship/patreon support of this project is a *donation* to help the development of this project. A donation with nothing in return, except for a patron role and early access to some experimental features *once they are done*. So its only logical that this isn't some kind of a trade, I don't sell any goods or services. And if there is no trade, there can't be any goods/services that are held back. There is no deceptive/fraudulent behavior here, so I really think your claims of this project possibly being a scam are unjustified.
Remember: All Donations are entirely voluntary, I don't "sell" anything, people just donate to support my work. If you don't like the idea of donating to a stranger, that's totally fine, you don't have to do it.
And if there really was a Patron who'd subscribe expecting to immediately receive free discord nitro, I'd totally refund the money, *even though I'm not obliged to do so*!
Its explicitly stated that subscribers don't receive free discord nitro by subscribing, so *technically* it would be their fault. But I am not like that. If someone really subscribed by accident (maybe because they don't understand English well, or for what ever reason) and messaged me about it, I really wouldn't hesitate refunding it. In fact I always talk to my Patrons and they always have the possibility to contact me, but no one ever did. Nobody ever asked for a refund, which is why I think its clear that the donations are donations.

At the end of the day, this is just a hobby project of mine and I want to use the donations to have more time for working on it. There is no financial incentive behind it, the only thing I'm trying to do is to make everyone's live better by improving the user experience of some discord users. (Which in turn leads to more engagement with the platform which also helps discord itself)

**Comment by hxr404** [comment]
@Anonymous941 
> one chance to prove yourself

I don't have to "prove" anything, I'm not forcing you or anyone to use this project or to donate. If you don't like this project stop thinking about it and just move on.


Also just because I can't reply to this thread within 4 days, it doesn't mean I'm ignoring it.


I'm only gonna reply to people with real feedback here, not to random accusations.


Something like

> this repo is full of shit fr, if it was possible to do what he is claiming, people would've done it ages before him
@Sxvxgee

doesn't contribute anything to this discussion and is at best off-topic, if not inappropriate, GitHub is a platform for Software Development, not for people getting mad about nothing.
That's why I'm not gonna reply to comments like these.

<hr>

So now I'm gonna reply to the only useful feedback in this issue:
First of all, thanks @CanadaHonk for your honest and neutral feedback, I appreciate that there are still people here who can say something without insults.


> best you could do is use a fake one for users of "Discord Oxygen".
And that's exactly the thing I'm doing here with this project. Most features that aren't possible "for real" are done client-side / changes only displays to other Discord Oxygen users.

other examples you mentioned are indeed possible,
for example the "Discord Mobile QR Exploit" is not only possible, but has been implemented by many other projects already. (Perhaps the lack of explanation what this exploit actually does could be misleading? I'm not really sure, because to me it seems self-explanatory)
This thing simply works by generating a QR Code which grants access to someone's account if scanned. It doesn't work remotely and isn't a zero-day it needs to be scanned by the "victim", so I don't really get why this couldn't be possible.
Things like "Fetch private information" also aren't really hard to do, I mean if you consider seeing the permissions of hidden channels private then literally anyone could do it. (I don't, but still)
One example of what that "exploit" does is monitoring the online / offline schedules of a specific user, and that's in my opinion really private information.

> Plus, use of them would be illegal and immoral.

That's why some of them are marked as private-only. And besides, how should some harmless client-modifications be illegal? I don't use any of Discord's assets or code, so there is no copyright infringement and even if some of the features were illegal (which I doubt they are, nobody is gonna get into jail for violating some Terms of Service), *I* am only publishing them, I'm not the one using them.
(Currently I'm not even publishing them, I only post *names* of features on a README, that isn't illegal and shouldn't be if freedom of speech exists.)

I really understand your concerns that some of the features may be immoral to use because discord is selling them and if people would get it for free it *could* harm discord's business.
But I carefully thought about this and I came to the conclusion, that this project won't harm Discord's revenue. I don't think people would stop buying Nitro just because some of it's features are made available by some random third-party. And, perhaps the most important reason, the target audience of this project are certainly not people who genuinely want to buy Nitro. Most people who see this repo come here, because they *don't* want to buy Nitro. So if they already made the decision that they don't want to buy it, this project doesn't change anything.
-> Therefore no loss for Discord but better user experience for some users. That's a win-win situation imho.
And if someone would lose their account due to the usage of this project, its a risk the user has to consider. I explicitly warn about that risk and everyone has to decide on their own.
Even though its not nice to loose an account, I don't think that's something immoral to support, especially not if the user makes an informed decision to take/not take that risk.

And to address your last argument that linking a sponsor button to this project might be "at best a scam" I have multiple answers.
1. "at best"? What could possibly be worse than a scam? I don't really understood what you wanted to say there, a clarification would be appreciated.
2. I have to disagree that this project couldn't accomplish what is stated on the readme. Even if things like changing a discriminator isn't possible globally, it *is* indeed possible to do that client-side and for other users of Discord Oxygen. So maybe the misunderstanding here is the definition of accomplishing things. I personally think, that if something works client-side and for other users of Discord Oxygen it is "accomplished". But yes, I have to agree with you that this maybe should be clarified a bit, as things looking obvious to me might not be obvious for many others, so thanks for pointing that out.
3. The sponsorship/patreon support of this project is a *donation* to help the development of this project. A donation with nothing in return, except for a patron role and early access to some experimental features *once they are done*. So its only logical that this isn't some kind of a trade, I don't sell any goods or services. And if there is no trade, there can't be any goods/services that are held back. There is no deceptive/fraudulent behavior here, so I really think your claims of this project possibly being a scam are unjustified.
Remember: All Donations are entirely voluntary, I don't "sell" anything, people just donate to support my work. If you don't like the idea of donating to a stranger, that's totally fine, you don't have to do it.
And if there really was a Patron who'd subscribe expecting to immediately receive free discord nitro, I'd totally refund the money, *even though I'm not obliged to do so*!
Its explicitly stated that subscribers don't receive free discord nitro by subscribing, so *technically* it would be their fault. But I am not like that. If someone really subscribed by accident (maybe because they don't understand English well, or for what ever reason) and messaged me about it, I really wouldn't hesitate refunding it. In fact I always talk to my Patrons and they always have the possibility to contact me, but no one ever did. Nobody ever asked for a refund, which is why I think its clear that the donations are donations.

At the end of the day, this is just a hobby project of mine and I want to use the donations to have more time for working on it. There is no financial incentive behind it, the only thing I'm trying to do is to make everyone's live better by improving the user experience of some discord users. (Which in turn leads to more engagement with the platform which also helps discord itself)

**Comment by CanadaHonk** [comment]
Not trying to cause greater conflict / drama / etc so closed.

**Comment by hxr404** [comment]
> I said immoral and illegal in terms of using exploits on people, not harming Discord's revenue

I see, seems like I got it wrong, sorry for that 

> I recommend renaming / adding detail things like "Discord Mobile QR Exploit", etc

Yeah I'll definitely do that. I didn't realize until now, that my language here isn't really clear for people who don't actually know how the different exploits work.



> Not trying to cause greater conflict / drama / etc so closed.

Thanks, I appreciate it, this issue here already was getting out of control.
In case there is still anything you want to discuss / there are any concerns with this project, please don't hesitate contacting me privately / opening a new issue/GitHub discussion. Honest feedback like yours is what really helps this project.

With that said, I'll lock this issue now.
<hr>

To anyone wondering: NO, this is not an attempt to "censor opinions I don't like" (it would be pointless anyways), I just want to maintain a healthy discussion environment free of personal insults, pointless off-topic comments, or opinionated rants.
If you really have something important & useful to say, please make a separate issue (consisting of concise and fact-based arguments) instead of adding comments. Thank You.

Also I didn't delete any messages here, I just hid the off-topic ones, you can still access them by clicking "view hidden comment".
