### ISSUE TITLE
Release date

### ISSUE THREAD

**Issue by FarisBlayz** [hxr404/Discord-Oxygen#20]
Hello, Sorry to bother you hxr404 since most likely you are working on the project or doing something in real-life, I wanted to know, Most projects have an estimated time of arrival, Does Discod-Oxygen too have an ETA or an ETOR (Estimated time of release), Thanks.

**Comment by hxr404** [comment]
No sorry, there's no ETA yet. The problem is that I'm a single Dev working on this and I can't really say in advance when I have free-time for coding, because one of my jobs is really irregular (and also depends on how much money I need in a particular month) and additionally predicting at what time I have to study how much is really hard. Therefore I can't realistically calculate how long it's gonna take.
The fact that discord regularly changes things which could break my code doesn't make it easier.

**Comment by Anonymous941** [comment]
@hxr404 can you give a screenshot of the unfinished project, a snippet of code or _anything_?  Anything at all?  It might help people be less suspicous of this project.  It doesn't matter what it is, and if you have literally nothing but a feature list after what is quickly approaching a year, I for one am going to stop paying atttention to this.

**Comment by demo308** [comment]
dude its 2023

**Comment by Anonymous941** [comment]
@demo308 This is a fake project designed to get attention and donation scams, obviously

**Comment by demo308** [comment]
Wait for it to release

**Comment by Anonymous941** [comment]
It's been years and not a single screenshot
