### ISSUE TITLE
Just to let you know.

### ISSUE THREAD

**Issue by Galaxzy345** [hxr404/Discord-Oxygen#6]
If half of these features in the README are true, such as grabbing a users token with a link, you know you could probably make some money reporting that to the Discord Bug Bounty. I also have some questions.

- How would it be possible to upload a 100GB file to Discord?
- How would it be possible to "become staff + certified moderator"?
- How would it be possible to send longer messages that bypass 2,000 or 4,000 char limit? They even have that protection on the server side. The only way I can see you pulling that off is with some funky text formatting.

How do plan to to login as a bot? If I am not mistaken, you cannot login to bot as you would with a user token. That would require you to create a separate client with Discord's Bot API, or something to that extent.

Let me know how you plan to achieve these.

**Comment by hxr404** [comment]
> How would it be possible to upload a 100GB file to Discord?

by uploading it to an external file hoster (and making it look like a normal discord upload)
and maybe (we still have to test performance) even using discord itself as the "external file hoster" in the rendering module. This would work by simply splitting the file in multiple chunks and uploading them to a hidden chat.

> How would it be possible to "become staff + certified moderator"?

well yeah maybe I should rewrite that paragraph to make things more clear. Its a combination of the "all badges hack" and enabling / re-implementig some hidden features (similar to the nitro "hack")

> How would it be possible to send longer messages that bypass 2,000 or 4,000 char limit? They even have that protection on the server side. The only way I can see you pulling that off is with some funky text formatting.

Haha, actually there was a (UI) bug which allowed to make 2 messages look like 1 (using "funky formatting / weird unicode characters), but its fixed.
Thats why we have to use a client-side rendering module (similar to the file-size bypass) to display bigger messages (and for compatibility with non-oxygen clients the message is simply spitted into multiple messages)

> How do plan to to login as a bot? If I am not mistaken, you cannot login to bot as you would with a user token. That would require you to create a separate client with Discord's Bot API, or something to that extent.

Using a seperate "Bot API" isn't really necessary you can simply use the same endpoints that user tokens use. Most request just work (maybe with slight modifications of the request, but generally the endpoints work). Things like discord.js / discord.py / etc. are just 3rd party libraries to make bot development easier.
Ofc some things don't just work equally for Bots and for users, e.g. joining servers and logging in.
Logging in for authenticating to the server to start a session isn't necessary. Logging in for storing the credentials in the cache is. Since most of the requests the client sends also works for bots they don't need to be modified, and for things like the login procedure we just write our own login function / patch the original one
(similar to flam3rboy's [bot client](https://github.com/Flam3rboy/discord-bot-client), if you look through the code you'll see that its essentially a [modified version of the regular client](https://github.com/Flam3rboy/discord-bot-client/blob/master/index.html), the difference is that we actually modify the users client instead of shipping a pre-modifed version)

I hope this cleared up some confusion
pls lmk if there's still smth I can clarify

**Comment by hxr404** [comment]
btw sorry for bad spelling and grammar I wrote this in a hurry

**Comment by Galaxzy345** [comment]
Thank you for clarifying, could you also elaborate on the feature: "Sending messages as another user", is this a visual glitch or are you using some other method?
